Update ani-cli

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -89,6 +89,10 @@ help_info() {
         Display a countdown to the next episode
       -U, --update
         Update the script
+      --mpvex
+        Use mpvEx player on Android
+      --dwupdate
+        Update the script from driftywinds' fork (github.com/driftywinds/ani-cli)
     Some example usages:
       %s -q 720p banana fish
       %s --skip -S 2 one piece
@@ -125,6 +129,30 @@ update_script() {
     fi
     exit 0
 }
+
+# --- custom local patch: dwupdate -----------------------------------------
+# Updates the script from a personal fork instead of upstream.
+# Kept as a standalone function (not a modification of update_script) so
+# future `git pull`/merge from upstream won't conflict with this block.
+dwupdate_script() {
+    info "[fork:$dwupdate_repo:$branch] Checking for Update.."
+    update="$($curl_exe --fail-with-body -sL -A "$agent" "https://raw.githubusercontent.com/$dwupdate_repo/$branch/ani-cli")" || die "[fork:$dwupdate_repo:$branch] Connection error: $update"
+    new_version="$(printf "%s" "$update" | sed -nE 's|^version_number="([^"]+)"$|\1|p')"
+    [ -z "$new_version" ] && die "[fork:$dwupdate_repo:$branch] Invalid response."
+    printf "%s" "$update" | grep -q "^version_number" || die "[fork:$dwupdate_repo:$branch] Invalid response."
+    update="$(printf "%s\n" "$update" | diff -u "$0" -)"
+    if [ -z "$update" ]; then
+        info "[fork:$dwupdate_repo:$branch] Script is up to date :) ($version_number)"
+    else
+        if printf "%s\n" "$update" | patch "$0" -; then
+            info "[fork:$dwupdate_repo:$branch] Updated: $version_number -> $new_version"
+        else
+            die "[fork:$dwupdate_repo:$branch] Failed to update. Read the above line!"
+        fi
+    fi
+    exit 0
+}
+# --- end custom local patch: dwupdate --------------------------------------
 
 # checks if dependencies are present
 dep_ch() {
@@ -312,6 +340,9 @@ play_episode() {
         debug) printf "All links:\n%s\nSelected link:\n%s\n" "$links" "$video_link" ;;
         android_mpv) nohup am start --user 0 -a android.intent.action.VIEW -d "$video_link" -n is.xyz.mpv/.MPVActivity -e "title" "${anime_title} Episode ${ep_no}" $player_extra_flags >/dev/null 2>&1 & ;;
         android_vlc) nohup am start --user 0 -a android.intent.action.VIEW -d "$video_link" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "${anime_title} Episode ${ep_no}" $player_extra_flags >/dev/null 2>&1 & ;;
+        # --- custom local patch: mpvex ---
+        android_mpvex) nohup am start --user 0 -a android.intent.action.VIEW -d "$video_link" -n app.marlboroadvance.mpvex/app.marlboroadvance.mpvex.ui.player.PlayerActivity -t 'video/*' $player_extra_flags >/dev/null 2>&1 & ;;
+        # --- end custom local patch: mpvex ---
         *flatpak*mpv*) flatpak run io.mpv.Mpv $skip_flag $player_extra_flags --force-media-title="${anime_title} Episode ${ep_no}" "$video_link" >/dev/null 2>&1 & ;;
         *mpv*)
             if [ "$no_detach" = 0 ]; then
@@ -430,6 +461,9 @@ histfile="$hist_dir/ani-hsts"
 
 source="${ANI_CLI_DEFAULT_SOURCE:-search}"
 branch="${ANI_CLI_BRANCH:-master}"
+# --- custom local patch: dwupdate setting ---
+dwupdate_repo="${ANI_CLI_DW_REPO:-driftywinds/ani-cli}"
+# --- end custom local patch: dwupdate setting ---
 
 while [ $# -gt 0 ]; do
     case "$1" in
@@ -496,6 +530,19 @@ while [ $# -gt 0 ]; do
             branch="${2:-$branch}"
             update_script
             ;;
+        # --- custom local patch: mpvex / dwupdate flags ---
+        --mpvex)
+            case "$(uname -a | cut -d " " -f 1,3-)" in
+                *ndroid*) player_function="android_mpvex" ;;
+                *) die "mpvEx is only available on Android" ;;
+            esac
+            ;;
+        --dwupdate)
+            dep_ch "patch"
+            branch="${2:-$branch}"
+            dwupdate_script
+            ;;
+        # --- end custom local patch: mpvex / dwupdate flags ---
         *) query="$(printf "%s" "$query $1" | sed 's|^ ||;s| |+|g')" ;;
     esac
     shift
